### ISSUE TITLE
Plugin crashes App on refresh [ANDROID]

### ISSUE THREAD

**Issue by YuriVivaldi** [Skyost/Bonsoir#42] opened 2022-05-27 15:18 UTC
**Describe the bug**
Crasches entire app on RESTART

**To Reproduce**
Launch a series of discoveries
Then click on RESTART, 

**Expected behavior**
The app should restart without crashes.

**Smartphone :**
 - Device: Pixel 4a
 - OS:Android 12

**Additional context**
This is the output:
```
E/AndroidRuntime(13414): FATAL EXCEPTION: NsdManager
E/AndroidRuntime(13414): Process: generic.package.name, PID: 13414
E/AndroidRuntime(13414): java.lang.IllegalArgumentException: listener not registered
E/AndroidRuntime(13414): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
E/AndroidRuntime(13414): 	at android.net.nsd.NsdManager.getListenerKey(NsdManager.java:496)
E/AndroidRuntime(13414): 	at android.net.nsd.NsdManager.stopServiceDiscovery(NsdManager.java:636)
E/AndroidRuntime(13414): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.dispose(BonsoirDiscoveryListener.kt:167)
E/AndroidRuntime(13414): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.dispose$default(BonsoirDiscoveryListener.kt:165)
E/AndroidRuntime(13414): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.onStartDiscoveryFailed(BonsoirDiscoveryListener.kt:86)
E/AndroidRuntime(13414): 	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:412)
E/AndroidRuntime(13414): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13414): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13414): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13414): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process (13414): Sending signal. PID: 13414 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by Skyost** [comment] 2022-05-29 12:50
Duplicate of #33. Should be fixed in the upcoming release.

**Closed by Skyost** 2022-05-29 12:50 UTC
Labels: bug
